// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usqnctdpzvehtpecxemb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzcW5jdGRwenZlaHRwZWN4ZW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDYzNDMsImV4cCI6MjA2NjU4MjM0M30.9KedUHXrnu0LUxkWDyUzg-t787asNplkzCQ4Z97LZ2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});